### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by MonitK** [openalgorithmdevelopers/ObsDataGenerator#1]
If you wish to use this repository, kindly cite us 

B. Singh and M. Kapoor, "A Framework for the Generation of Obstacle Data for the Study of Obstacle Detection by Ultrasonic Sensors," in IEEE Sensors Journal, vol. 21, no. 7, pp. 9475-9483, 1 April1, 2021, doi: 10.1109/JSEN.2021.3055515.

**Comment by MonitK** [comment]
Add this issue to Readme.md and close this @openalgorithmdevelopers  bhupender sir

**Comment by openalgorithmdevelopers** [comment]
License file has been added and the readme has also been updated.
